### ISSUE TITLE
Broken after this update

### ISSUE THREAD

**Issue by sandikata** [PRATAP-KUMAR/bring-out-submenu-of-power-off-logout#24]
Hello, this extension seems to be broken after this update.
![Screenshot 2022-05-11 at 08-40-16 Bring Out Submenu Of Power Off_Logout Button - GNOME Shell Extensions](https://user-images.githubusercontent.com/884699/167776704-dd8fb23b-52ff-42bc-9d14-069a70c74874.png)

**Comment by pratap-panabaka** [comment]
Hi yesterday i did a small error correction and updated. I can't see the error from your screenshot. Have you logut and logged in. What's your gnome-shell version

Thanks

**Comment by sandikata** [comment]
gnome shell 42 it was working since this update, and yes gnome shell was restarted.

**Comment by pratap-panabaka** [comment]
Logged out n logged in or gnome-shell restart?
Is it possible to logout and login back please?

**Comment by pratap-panabaka** [comment]
I guess you are using the browser extension to manage gnome-shell-extensions..
I remember this case in the past, there are some sync issues. Some of the users mentioned that after a restart the problem is gnome.

when I did the correction yesterday and after update from gnome-extensions.. the v29 is working fine in my system.

![Screenshot from 2022-05-11 11-32-33](https://user-images.githubusercontent.com/40719899/167779609-129c4e8d-b4c2-4809-abda-c2c49bde0d67.png)

**Comment by sandikata** [comment]
I can confirm it works after reboot.
But one question, is it possible to be extended, just to separate all the things from this menu directly to the panel?

**Comment by pratap-panabaka** [comment]
You mean powerOff as a seperate button on top right side of the panel plus restart, logout, switch user etc??

**Comment by sandikata** [comment]
I mean all of them, power off as separate on the panel, Wi-Fi sound Bluetooth Network Sound the same. (If it's possible)

Regards,
Rosen Aleksandrov

**Comment by pratap-panabaka** [comment]
Can you make a rough sketch.. I understand what you mean and it is possible too.. rite now I am not able to spend much time. Provide a sketch if possible, I will try it on weekends.

Thanks
